//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiwarehouseMgt
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class NewRequestTable
    {
        public int Id { get; set; }
        [DisplayName("Name Of Book")]
        public string BookName { get; set; }
        [DisplayName("Location of Book")]
        public string LocationName { get; set; }
        [DisplayName("Date Of request")]
        public Nullable<System.DateTime> DateAdded { get; set; }
        [DisplayName("Requester Name")]

        public string AddedBy { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
