//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiwarehouseMgt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Id { get; set; }
        public Nullable<int> BookRequestedId { get; set; }
        public Nullable<System.DateTime> DateRequested { get; set; }
        public string RequestedBy { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
